# Generated by Django 5.0.1 on 2024-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
