# Generated by Django 4.2.9 on 2024-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedGrantApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="grantapp/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
