# Generated by Django 4.2.9 on 2024-05-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="documents",
            field=models.JSONField(default=list),
        ),
    ]
