# Generated by Django 4.2.9 on 2024-05-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_alter_uploadedgrantapp_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedGrantApp",
        ),
    ]
