# Generated by Django 4.2.9 on 2024-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0004_delete_uploadedgrantapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
    ]
